# Generated by Django 4.2.30 on 2026-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_role_lost_mode_perms"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_manage_asset_intake",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="can_view_erase_certificates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="can_wipe_device",
            field=models.BooleanField(default=False),
        ),
    ]
