# Generated by Django 4.2.30 on 2026-08-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0025_site_latitude_site_longitude"),
        ("agents", "0068_agent_outside_geofence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetIntake",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_id", models.CharField(max_length=64, unique=True)),
                (
                    "equipment_serial",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "media_serial",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("asset_tag", models.CharField(blank=True, default="", max_length=255)),
                (
                    "ticket_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "delivered_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("received_by", models.CharField(max_length=255)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("functional", "Funcional"),
                            ("non_functional", "No funcional"),
                            ("no_media", "Sin medio detectable"),
                        ],
                        default="functional",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_intakes",
                        to="agents.agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_intakes",
                        to="clients.client",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_intakes",
                        to="clients.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WipeOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_hostname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "agent_serial",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("crypto_erase", "Crypto-erase remoto"),
                            ("wipe", "Wipe selectivo por rutas"),
                            ("fullwipe", "Borrado total del volumen de datos"),
                            ("factoryreset", "Restauración de fábrica"),
                        ],
                        max_length=32,
                    ),
                ),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("dry_run", models.BooleanField(default=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("lost_mode_cycle", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            (
                                "pending_confirmation",
                                "Pendiente de segunda confirmación",
                            ),
                            ("confirmed", "Confirmada"),
                            ("recovery_window", "En ventana de arrepentimiento"),
                            ("dispatched", "Despachada al equipo"),
                            ("cancelled", "Cancelada"),
                            ("executed", "Ejecutada"),
                            ("failed", "Fallida"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("ordered_by", models.CharField(max_length=255)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wipe_orders",
                        to="agents.agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wipe_orders",
                        to="clients.client",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wipe_orders",
                        to="clients.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="EraseCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "prev_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "record_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("certificate_id", models.CharField(max_length=64, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "remote_destruction",
                                "Destrucción remota / borrado lógico",
                            ),
                            ("physical_destruction", "Destrucción física"),
                        ],
                        max_length=32,
                    ),
                ),
                ("tenant", models.CharField(max_length=255)),
                ("asset_tag", models.CharField(blank=True, default="", max_length=255)),
                (
                    "method_applied",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "standard_ref",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "verification_result",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("operator", models.CharField(blank=True, default="", max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "software_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("data", models.JSONField(default=dict)),
                ("document_hash", models.CharField(max_length=64)),
                ("signature", models.TextField(blank=True, default="")),
                (
                    "signature_alg",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "signing_key_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erase_certificates",
                        to="agents.agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erase_certificates",
                        to="clients.client",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="erase.assetintake",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="erase.wipeorder",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erase_certificates",
                        to="clients.site",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EraseAuditRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "prev_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "record_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("agent_id", models.CharField(blank=True, default="", max_length=255)),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("event", models.CharField(max_length=64)),
                ("actor", models.CharField(blank=True, default="", max_length=255)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_records",
                        to="erase.wipeorder",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
