# Generated by Django 4.2.30 on 2026-08-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erase", "0003_wipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retrievedfile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
