# Generated by Django 4.2.30 on 2026-07-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_coresettings_geo_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresettings',
            name='geo_force_location_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='geo_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
