# Generated by Django 4.2.30 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_geo_defaults_on_instalacion_nueva"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="open_ai_base_url",
            field=models.CharField(
                blank=True, default="https://api.openai.com/v1", max_length=255
            ),
        ),
    ]
