# Generated by Django 4.2.30 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_coresettings_open_ai_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="open_ai_max_tokens",
            field=models.PositiveIntegerField(default=4000),
        ),
    ]
