# Generated by Django 4.2.30 on 2026-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_rename_sync_mesh_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='maintenance_alert_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='maintenance_alert_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
