# Generated by Django 4.2.30 on 2026-08-12 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_coresettings_maintenance_alert_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_evidence_closed_case_days',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_evidence_prune_days',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
