# Generated by Django 4.2.30 on 2026-08-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_coresettings_lost_mode_evidence_closed_case_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_webcam_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
