# Generated by Django 4.2.30 on 2026-08-21 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_coresettings_lost_mode_webcam_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_alarm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_auto_lock_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_lock_delay_min',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_no_hibernate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='lost_mode_webcam_override_default',
            field=models.BooleanField(default=True),
        ),
    ]
