# Generated by Django 4.2.30 on 2026-08-26 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_coresettings_open_wifi_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="erase_attachment_retention_days",
            field=models.PositiveIntegerField(
                default=365, validators=[django.core.validators.MinValueValidator(365)]
            ),
        ),
    ]
