# Generated by Django 4.2.30 on 2026-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0062_agent_geo_offsite_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='maintenance_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='maintenance_mode_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='maintenance_mode_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
