# Generated by Django 4.2.30 on 2026-08-12 00:37

import agents.lostmode_storage
import agents.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0063_agent_maintenance_alert_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostModeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('reason', models.TextField(default='')),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('interval_min', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_mode', to='agents.agent')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_mode_markings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LostModeEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cycle', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('screen', 'Screen Capture'), ('webcam', 'Webcam Picture'), ('geo', 'Location Fix')], max_length=20)),
                ('asset', models.FileField(blank=True, null=True, storage=agents.lostmode_storage.get_lost_mode_evidence_fs, upload_to=agents.models.lost_mode_evidence_path)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('session_user', models.CharField(blank=True, max_length=255, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_mode_evidence', to='agents.agent')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['agent', 'cycle'], name='agents_lost_agent_i_12b715_idx')],
            },
        ),
    ]
