# Generated by Django 4.2.30 on 2026-08-17 19:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0065_lostmodeevidence_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskEncryptionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported', models.BooleanField(default=True)),
                ('query_error', models.TextField(blank=True, null=True)),
                ('measured_at', models.DateTimeField()),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disk_encryption', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='DiskEncryptionVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('drive_letter', models.CharField(blank=True, max_length=10, null=True)),
                ('protection_status', models.PositiveSmallIntegerField()),
                ('conversion_status', models.PositiveSmallIntegerField()),
                ('encryption_method', models.PositiveSmallIntegerField()),
                ('encryption_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume_type', models.PositiveSmallIntegerField()),
                ('is_system_volume', models.BooleanField(default=False)),
                ('key_protector_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('key_protector_types', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None)),
                ('measured_at', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_encryption_volumes', to='agents.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['is_system_volume', 'protection_status'], name='agents_disk_is_syst_279231_idx')],
                'unique_together': {('agent', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='DiskEncryptionHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('previous_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_status', models.PositiveSmallIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_encryption_history', to='agents.agent')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['agent', 'device_id'], name='agents_disk_agent_i_d658a1_idx')],
            },
        ),
    ]
