# Generated by Django 4.2.30 on 2026-08-21 00:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0066_diskencryptionstate_diskencryptionvolume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostmodestate',
            name='cascade_alarm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostmodestate',
            name='cascade_auto_lock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostmodestate',
            name='cascade_lock_delay_min',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='lostmodestate',
            name='cascade_no_hibernate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostmodestate',
            name='cascade_webcam_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LostModePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_lock', models.BooleanField(blank=True, null=True)),
                ('lock_delay_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('no_hibernate', models.BooleanField(blank=True, null=True)),
                ('webcam_override', models.BooleanField(blank=True, null=True)),
                ('alarm', models.BooleanField(blank=True, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_mode_policy', to='agents.agent')),
            ],
        ),
    ]
