---
- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: systemd daemon-reload

- name: restart meshcentral
  ansible.builtin.systemd:
    name: meshcentral
    state: restarted
  listen: restart meshcentral
