---
- name: restart postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ observer_postgresql_version }}-main"
    state: restarted
  listen: restart postgresql

- name: reload postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ observer_postgresql_version }}-main"
    state: reloaded
  listen: reload postgresql
